# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: blog.privacytools.io
email: admin@privacytools.io
description: >- # this means to ignore newlines until "baseurl:"
  The official blog from the privacytools.io team! Discover new ways to enhance your privacy and security online, hear announcements from the team, and keep up with privacy-related news.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.privacytools.io" # the base hostname & protocol for your site, e.g. http://example.com
sass:
    sass_dir: _sass
excerpt_separator: <!--more-->
collections_dir: collections
collections:
  authors:
    title: Authors
    output: true

defaults:
- scope:
    path: ''
    type: authors
  values:
    permalink: "/authors/:title/"
    layout: author
    position: Contributor
    mastodon:
    twitter:
    website:
    github:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/posts/:title/"
    layout: post
    author:
    tags:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

gems:
- jekyll/tagging

tag_page_layout: tag
tag_page_dir: tags
paginate: 6
paginate_path: "/page:num/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
